name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true   # <--- ini penting, otomatis ambil file LFS

      - name: Install Git LFS manually (backup)
        run: |
          git lfs install
          git lfs pull

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: echo $CSV_URL

      # A1: Save in Local Github
      # Install mlflow
      - name: Install dependencies mlflow
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      - name: Set up Git LFS
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main

      # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
      
      # A2: Save in Google Drive
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install mlflow google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # - name: Run mlflow project
      #   run: mlflow run MLproject --env-manager=local

      # # ✅ Upload ke Google Drive (bukan Git)
      # - name: Upload to Google Drive
      #   env:
      #     GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      #     GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      #   run: python MLproject/upload_to_gdrive.py